#!/bin/sh

start() {
    fw_printenv > /tmp/fw_printenv.out
    if grep "upgrade_available=1" /tmp/fw_printenv.out ; then
        logger -t $0 "Recent mender upgrade was a success. Committing."
        mender commit
    else
        logger -t $0 "No upgrade in process; nothing to do"
    fi
}

stop() {
    # Nothing to do
    :
}

restart() {
    stop
    start
}

case "$1" in
        start)
                start
                ;;
        stop)        
                stop
                ;;
        restart|reload)
                restart
                ;;     
        *)             
                echo "Usage: $0 {start|stop|reload|restart}"
                exit 1
esac                                                        
                      
exit $?

